version: "3.8"

services:

  # Application service
  edge-service:
    depends_on:
      - postgres-service
      - redis-service
      - keycloak-service
      - api-service
#      - chat-ui # disable to chat-ui be served standalone
    image: 'cncf-edge-service'
    container_name: 'edge-service'
    ports:
      - '9000:9000'
      - '8000:8000'
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - API_SERVICE_URL=http://api-service:9001
      - UI_SERVICE_URL=http://chat-ui:4200
      - SPRING_DATA_REDIS_HOST=redis-service
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/chat
  
  # Chat service
  api-service:
    image: 'cncf-api-service'
    container_name: 'api-service'
    depends_on:
      - postgres-service
    ports:
      - '9001:9001'
      - '8001:8001'
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - BPL_JVM_THREAD_COUNT=50
      - KEYCLOAK_AUTH_SERVER_URL=http://host.docker.internal:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/main_db
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/chat

  # Chat UI service
  chat-ui:
    image: 'chat-ui'
    container_name: 'chat-ui'
    ports:
      - '9004:9004'
    environment:
    - PORT=9004

  # Postgres service
  postgres-service:
    image: postgres:16
    container_name: postgres-service
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  # Redis service
  redis-service:
    image: "redis:7.0"
    container_name: "redis-service"
    ports:
      - '6379:6379'

  # Keycloak service
  keycloak-service:
    image: 'quay.io/keycloak/keycloak:23.0'
    container_name: 'keycloak-service'
    depends_on:
      - postgres-service
    restart: always
    command: start-dev --import-realm --features=preview
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
      - KC_DB_URL=jdbc:postgresql://postgres-service:5432/keycloak_db
      - KC_FEATURES=scripts
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - '8080:8080'